# =============================================================================
# Ansible Role: Docker - Molecule Preparation Playbook (Uninstall Scenario)
# =============================================================================

---
- name: Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: Prepare | Disable EPEL repository (RedHat)
      ansible.builtin.shell: |
        if [ -f /etc/yum.repos.d/epel.repo ]; then
          sed -i 's/enabled=1/enabled=0/g' /etc/yum.repos.d/epel*.repo || true
        fi
      failed_when: false
      changed_when: false
      when: ansible_facts['os_family'] == "RedHat"

    - name: Prepare | Fix /etc/shadow permissions
      ansible.builtin.file:
        path: /etc/shadow
        mode: "0400"
      failed_when: false
