# =============================================================================
# Ansible Role: Docker - Molecule Convergence Playbook (Logging Override Scenario)
# =============================================================================

---
- name: Converge | Install Docker with explicit rsyslog log owner override
  hosts: all

  pre_tasks:
    - name: Converge | Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"

    - name: Converge | Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: ansible_facts['os_family'] == "RedHat"

  roles:
    - role: ../../..
      vars:
        docker_configure_rsyslog: true
        docker_rsyslog_log_file_owner: "nobody"
        # Disable service restarts and augenrules execution in container test environment
        docker_manage_service_restart: false
        docker_logrotate_options:
          frequency: "weekly"
          count: 12
          missingok: true
          compress: true
          nocreate: false
          dateext: true
          archive_directory_path: "{{ docker_log_directory_path }}"
          copytruncate: false
