---
# Docker Audit — Configure auditd rule for docker.sock monitoring.

- name: Docker | audit | Check if auditctl exists
  become: true
  ansible.builtin.stat:
    path: /sbin/auditctl
  register: __docker_auditctl

- name: Docker | audit | Configure audit rule for /var/run/docker.sock
  become: true
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/docker.rules
    state: present
    create: true
    line: "-w /var/run/docker.sock -p wa -k docker-sock"
    mode: '0644'
  when:
    - __docker_auditctl.stat.exists
  notify: Docker | handlers | Restart auditd
