---
# =============================================================================
# Ansible Role: Docker - Tasks: User-defined Networks
# =============================================================================
# Creates user-defined Docker networks using community.docker module.
# =============================================================================

- name: Docker | network | Create user-defined networks
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    ipam_config: >-
      {{ [{'subnet': item.subnet}] if item.subnet is defined else omit }}
    state: present
  loop: "{{ docker_networks }}"
  when:
    - item.name is defined
