---
# Docker Handlers — Service management operations triggered by tasks.

- name: Docker | handlers | Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - ansible_facts['service_mgr'] == 'systemd'

- name: Docker | handlers | Restart docker service
  become: true
  ansible.builtin.service:
    name: "{{ __docker_service_name }}"
    state: restarted
  when:
    - not (ansible_virtualization_type is defined and ansible_virtualization_type == 'docker')

- name: Docker | handlers | Restart rsyslog
  become: true
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when:
    - not (ansible_virtualization_type is defined and ansible_virtualization_type == 'docker')

- name: Docker | handlers | Restart auditd
  become: true
  ansible.builtin.service:
    name: auditd
    state: restarted
  when:
    - not (ansible_virtualization_type is defined and ansible_virtualization_type == 'docker')
