---
role_name_check: 1

dependency:
  name: galaxy
  options:
    ignore-errors: true

driver:
  name: docker

platforms:
  - name: debian12
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /lib/modules:/lib/modules:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    capabilities:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
  - name: debian11
    image: "geerlingguy/docker-debian11-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /lib/modules:/lib/modules:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    capabilities:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
  - name: ubuntu2404
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /lib/modules:/lib/modules:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    capabilities:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
  - name: ubuntu2204
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /lib/modules:/lib/modules:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    capabilities:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
  - name: rockylinux9
    image: "geerlingguy/docker-rockylinux9-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /lib/modules:/lib/modules:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    capabilities:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    verify: ${MOLECULE_PLAYBOOK:-verify.yml}
    prepare: ${MOLECULE_PLAYBOOK:-prepare.yml}
  lint:
    name: ansible-lint
  config_options:
    defaults:
      interpreter_python: auto_silent
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "true"

verifier:
  name: ansible
  options:
    verbose: true
