# =============================================================================
# Ansible Role: Docker - Molecule Convergence Playbook (Logging Scenario)
# =============================================================================

---
- name: Converge | Install Docker with Rsyslog logging enabled
  hosts: all

  pre_tasks:
    - name: Converge | Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"

    - name: Converge | Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: ansible_facts['os_family'] == "RedHat"

  roles:
    - role: ../../..
      vars:
        docker_configure_rsyslog: true
